

# Set the theme
[theme]
primaryColor = "#6d28d9"  
backgroundColor = "#101820"  
secondaryBackgroundColor = "#FEE715"  
textColor = "#e91730"  


# Set the layout
[server]
port = 8501
headless = false
enableCORS = false
enableXsrfProtection = true

